name: fireflutter
description: A free, open source, complete, rapid development package for creating Social apps, Chat apps, Community(Forum) apps, Shopping mall apps, and much more based on Firebase.
version: 0.2.14
homepage: https://github.com/thruthesky/fireflutter

environment:
  sdk: ">=2.15.0 <3.0.0"
  flutter: ">=2.2.0"

dependencies:
  flutter:
    sdk: flutter

  # Firebase
  firebase_core: ^1.10.6
  firebase_auth: ^3.3.4
  firebase_database: ^9.0.4
  cloud_firestore: ^3.1.6
  firebase_dynamic_links: ^4.0.5
  firebase_storage: ^10.2.6
  firebase_messaging: ^11.2.6

  # Firebase UI.
  flutterfire_ui: ^0.3.2

  rxdart: ^0.27.3

  # File upload
  path_provider: ^2.0.8
  image_picker: ^0.8.4+6
  flutter_image_compress: ^1.1.0
  photo_view: ^0.13.0
  
  # Caching uploaded image
  cached_network_image: ^3.2.0

  # PhoneNumberInput widget
  country_code_picker: ^2.0.2

  # Chat room pagination. firestore pagination ui helper.
  paginate_firestore: ^1.0.3

  # chat badge
  badges: ^2.0.2

  # geocoding, geolocator, google_maps_flutter, flutter_polyline_points are for `Find Friend`.
  geocoding: ^2.0.1
  geolocator: ^8.0.3
  google_maps_flutter: ^2.1.1
  flutter_polyline_points: ^1.0.0

  # reminder service,
  shared_preferences: ^2.0.12

  # date & time
  intl: ^0.17.0

  # uuid
  uuid: ^3.0.5

  # color picker for admin category management screen
  flutter_colorpicker: ^1.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
